# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d60fdf3ae3f98d68978e235c11dc78b34319cdd6380801fcf431d6511f6aceb0dfd68a6790d6ab0501970fad61f81fccd6ba14adf9e6ad545a3d3f8edb06441

test:
  secret_key_base: e3e69ea5bade48d80c360336fc8901f10005098eddb7814d9d99a4e840f74af4496b5da42ad2c60479178d64e028b8a3ab30c0326071c748098dc88286a6e194

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
